function updateHotline() {
  var countrySelect = document.getElementById("countrySelect");
  var selectedCountry = countrySelect.options[countrySelect.selectedIndex].value;
  var hotlineInfo = document.getElementById("hotlineInfo");

  // Define the hotline information for each country
  var hotlineData = {
    "Select_Country": "Select a country first",
    "Afghanistan": "Call 119 for scam prevention hotline in Afghanistan",
    "Albania": "Call 116 for scam prevention hotline in Albania",
    "Algeria": "Call 3030 for scam prevention hotline in Algeria",
    "Andorra": "Call 116 for scam prevention hotline in Andorra",
    "Angola": "Call 113 for scam prevention hotline in Angola",
    "Antigua and Barbuda": "Call 911 for scam prevention hotline in Antigua and Barbuda",
    "Argentina": "Call 0800-222-2222 for scam prevention hotline in Argentina",
    "Armenia": "Call 911 for scam prevention hotline in Armenia",
    "Australia": "Call 1800-007-007 for scam prevention hotline in Australia",
    "Austria": "Call 0800-222-555 for scam prevention hotline in Austria",
    "Azerbaijan": "Call 990 for scam prevention hotline in Azerbaijan",
    "Bahamas": "Call 919 for scam prevention hotline in Bahamas",
    "Bahrain": "Call 992 for scam prevention hotline in Bahrain",
    "Bangladesh": "Call 999 or 01777787878 for scam prevention hotline in Bangladesh",
    "Barbados": "Call 211 for scam prevention hotline in Barbados",
    "Belarus": "Call 102 for scam prevention hotline in Belarus",
    "Belgium": "Call 070-245-245 for scam prevention hotline in Belgium",
    "Belize": "Call 911 for scam prevention hotline in Belize",
    "Benin": "Call 117 for scam prevention hotline in Benin",
    "Bhutan": "Call 113 for scam prevention hotline in Bhutan",
    "Bolivia": "Call 110 for scam prevention hotline in Bolivia",
    "Bosnia and Herzegovina": "Call 122 for scam prevention hotline in Bosnia and Herzegovina",
    "Botswana": "Call 999 for scam prevention hotline in Botswana",
    "Brazil": "Call 151 for scam prevention hotline in Brazil",
    "Brunei": "Call 993 for scam prevention hotline in Brunei",
    "Bulgaria": "Call 166 for scam prevention hotline in Bulgaria",
    "Burkina Faso": "Call 17 for scam prevention hotline in Burkina Faso",
    "Burundi": "Call 117 for scam prevention hotline in Burundi",
    "Cabo Verde": "Call 132 for scam prevention hotline in Cabo Verde",
    "Cambodia": "Call 110 for scam prevention hotline in Cambodia",
    "Cameroon": "Call 117 for scam prevention hotline in Cameroon",
    "Canada": "Call 1-888-495-8501 for scam prevention hotline in Canada",
    "Central African Republic": "Call 117 for scam prevention hotline in Central African Republic",
    "Chad": "Call 17 for scam prevention hotline in Chad",
    "Chile": "Call 146 for scam prevention hotline in Chile",
    "China": "Call 110 for scam prevention hotline in China",
    "Colombia": "Call 165 for scam prevention hotline in Colombia",
    "Comoros": "Call 17 for scam prevention hotline in Comoros",
    "Congo, Democratic Republic of the Congo": "Call 117 for scam prevention hotline in Congo, Democratic Republic of the Congo",
    "Congo, Republic of the Congo": "Call 117 for scam prevention hotline in Congo, Republic of the Congo",
    "Costa Rica": "Call 1176 for scam prevention hotline in Costa Rica",
    "Croatia": "Call 192 for scam prevention hotline in Croatia",
    "Cuba": "Call 106 for scam prevention hotline in Cuba",
    "Cyprus": "Call 1460 for scam prevention hotline in Cyprus",
    "Czech Republic": "Call 158 for scam prevention hotline in Czech Republic",
    "Denmark": "Call 112 for scam prevention hotline in Denmark",
    "Djibouti": "Call 17 for scam prevention hotline in Djibouti",
    "Dominica": "Call 911 for scam prevention hotline in Dominica",
    "Dominican Republic": "Call 911 for scam prevention hotline in Dominican Republic",
    "Ecuador": "Call 1800-DELITO (1800-335486) for scam prevention hotline in Ecuador",
    "Egypt": "Call 16516 for scam prevention hotline in Egypt",
    "El Salvador": "Call 911 for scam prevention hotline in El Salvador",
    "Equatorial Guinea": "Call 117 for scam prevention hotline in Equatorial Guinea",
    "Eritrea": "Call 113 for scam prevention hotline in Eritrea",
    "Estonia": "Call 112 for scam prevention hotline in Estonia",
    "Eswatini": "Call 999 for scam prevention hotline in Eswatini",
    "Ethiopia": "Call 8335 for scam prevention hotline in Ethiopia",
    "Fiji": "Call 917 for scam prevention hotline in Fiji",
    "Finland": "Call 112 for scam prevention hotline in Finland",
    "France": "Call 17 for scam prevention hotline in France",
    "Gabon": "Call 1730 for scam prevention hotline in Gabon",
    "Gambia": "Call 117 for scam prevention hotline in Gambia",
    "Georgia": "Call 112 for scam prevention hotline in Georgia",
    "Germany": "Call 0800-123-123 for scam prevention hotline in Germany",
    "Ghana": "Call 18555 for scam prevention hotline in Ghana",
    "Greece": "Call 110 for scam prevention hotline in Greece",
    "Grenada": "Call 911 for scam prevention hotline in Grenada",
    "Guatemala": "Call 110 for scam prevention hotline in Guatemala",
    "Guinea": "Call 117 for scam prevention hotline in Guinea",
    "Guinea-Bissau": "Call 117 for scam prevention hotline in Guinea-Bissau",
    "Guyana": "Call 911 for scam prevention hotline in Guyana",
    "Haiti": "Call 114 for scam prevention hotline in Haiti",
    "Honduras": "Call 911 for scam prevention hotline in Honduras",
    "Hungary": "Call 112 for scam prevention hotline in Hungary",
    "Iceland": "Call 112 for scam prevention hotline in Iceland",
    "India": "Call 155260 for scam prevention hotline in India",
    "Indonesia": "Call 119 for scam prevention hotline in Indonesia",
    "Iran": "Call 110 for scam prevention hotline in Iran",
    "Iraq": "Call 112 for scam prevention hotline in Iraq",
    "Ireland": "Call 112 for scam prevention hotline in Ireland",
    "Israel": "Call 105 for scam prevention hotline in Israel",
    "Italy": "Call 117 for scam prevention hotline in Italy",
    "Jamaica": "Call 119 for scam prevention hotline in Jamaica",
    "Japan": "Call 110 for scam prevention hotline in Japan",
    "Jordan": "Call 911 for scam prevention hotline in Jordan",
    "Kazakhstan": "Call 102 for scam prevention hotline in Kazakhstan",
    "Kenya": "Call 999 for scam prevention hotline in Kenya",
    "Kiribati": "Call 192 for scam prevention hotline in Kiribati",
    "Korea, North": "Call 119 for scam prevention hotline in Korea, North",
    "Korea, South": "Call 112 for scam prevention hotline in Korea, South",
    "Kosovo": "Call 192 for scam prevention hotline in Kosovo",
    "Kuwait": "Call 112 for scam prevention hotline in Kuwait",
    "Kyrgyzstan": "Call 102 for scam prevention hotline in Kyrgyzstan",
    "Laos": "Call 1190 for scam prevention hotline in Laos",
    "Latvia": "Call 110 for scam prevention hotline in Latvia",
    "Lebanon": "Call 112 for scam prevention hotline in Lebanon",
    "Lesotho": "Call 123 for scam prevention hotline in Lesotho",
    "Liberia": "Call 911 for scam prevention hotline in Liberia",
    "Libya": "Call 1515 for scam prevention hotline in Libya",
    "Liechtenstein": "Call 117 for scam prevention hotline in Liechtenstein",
    "Lithuania": "Call 112 for scam prevention hotline in Lithuania",
    "Luxembourg": "Call 113 for scam prevention hotline in Luxembourg",
    "Madagascar": "Call 117 for scam prevention hotline in Madagascar",
    "Malawi": "Call 997 for scam prevention hotline in Malawi",
    "Malaysia": "Call 997 for scam prevention hotline in Malaysia",
    "Maldives": "Call 119 for scam prevention hotline in Maldives",
    "Mali": "Call 17 for scam prevention hotline in Mali",
    "Malta": "Call 112 for scam prevention hotline in Malta",
    "Marshall Islands": "Call 911 for scam prevention hotline in Marshall Islands",
    "Mauritania": "Call 116 for scam prevention hotline in Mauritania",
    "Mauritius": "Call 113 for scam prevention hotline in Mauritius",
    "Mexico": "Call 089 for scam prevention hotline in Mexico",
    "Micronesia": "Call 911 for scam prevention hotline in Micronesia",
    "Moldova": "Call 112 for scam prevention hotline in Moldova",
    "Monaco": "Call 17 for scam prevention hotline in Monaco",
    "Mongolia": "Call 102 for scam prevention hotline in Mongolia",
    "Montenegro": "Call 122 for scam prevention hotline in Montenegro",
    "Morocco": "Call 190 for scam prevention hotline in Morocco",
    "Mozambique": "Call 117 for scam prevention hotline in Mozambique",
    "Myanmar": "Call 199 for scam prevention hotline in Myanmar",
    "Namibia": "Call 10111 for scam prevention hotline in Namibia",
    "Nauru": "Call 110 for scam prevention hotline in Nauru",
    "Nepal": "Call 100 for scam prevention hotline in Nepal",
    "Netherlands": "Call 0900-8844 for scam prevention hotline in Netherlands",
    "New Zealand": "Call 0508 638 723 for scam prevention hotline in New Zealand",
    "Nicaragua": "Call 118 for scam prevention hotline in Nicaragua",
    "Nigeria": "Call 0700-2255-6327 for scam prevention hotline in Nigeria",
    "North Macedonia": "Call 192 for scam prevention hotline in North Macedonia",
    "Norway": "Call 02800 for scam prevention hotline in Norway",
    "Oman": "Call 9999 for scam prevention hotline in Oman",
    "Pakistan": "Call 9911 for scam prevention hotline in Pakistan",
    "Palau": "Call 911 for scam prevention hotline in Palau",
    "Panama": "Call 311 for scam prevention hotline in Panama",
    "Papua New Guinea": "Call 111 for scam prevention hotline in Papua New Guinea",
    "Paraguay": "Call 911 for scam prevention hotline in Paraguay",
    "Peru": "Call 105 for scam prevention hotline in Peru",
    "Philippines": "Call 911 for scam prevention hotline in Philippines",
    "Poland": "Call 112 for scam prevention hotline in Poland",
    "Portugal": "Call 112 for scam prevention hotline in Portugal",
    "Qatar": "Call 999 for scam prevention hotline in Qatar",
    "Romania": "Call 112 for scam prevention hotline in Romania",
    "Russia": "Call 112 for scam prevention hotline in Russia",
    "Rwanda": "Call 112 for scam prevention hotline in Rwanda",
    "Saint Kitts and Nevis": "Call 911 for scam prevention hotline in Saint Kitts and Nevis",
    "Saint Lucia": "Call 911 for scam prevention hotline in Saint Lucia",
    "Saint Vincent and the Grenadines": "Call 911 for scam prevention hotline in Saint Vincent and the Grenadines",
    "Samoa": "Call 995 for scam prevention hotline in Samoa",
    "San Marino": "Call 112 for scam prevention hotline in San Marino",
    "Sao Tome and Principe": "Call 112 for scam prevention hotline in Sao Tome and Principe",
    "Saudi Arabia": "Call 999 for scam prevention hotline in Saudi Arabia",
    "Senegal": "Call 800-200-200 for scam prevention hotline in Senegal",
    "Serbia": "Call 192 for scam prevention hotline in Serbia",
    "Seychelles": "Call 133 for scam prevention hotline in Seychelles",
    "Sierra Leone": "Call 019 for scam prevention hotline in Sierra Leone",
    "Singapore": "Call 1800-722-6688 for scam prevention hotline in Singapore",
    "Slovakia": "Call 112 for scam prevention hotline in Slovakia",
    "Slovenia": "Call 113 for scam prevention hotline in Slovenia",
    "Solomon Islands": "Call 999 for scam prevention hotline in Solomon Islands",
    "Somalia": "Call 888 for scam prevention hotline in Somalia",
    "South Africa": "Call 10111 for scam prevention hotline in South Africa",
    "South Sudan": "Call 111 for scam prevention hotline in South Sudan",
    "Spain": "Call 112 for scam prevention hotline in Spain",
    "Sri Lanka": "Call 119 for scam prevention hotline in Sri Lanka",
    "Sudan": "Call 999 for scam prevention hotline in Sudan",
    "Suriname": "Call 115 for scam prevention hotline in Suriname",
    "Sweden": "Call 113 13 for scam prevention hotline in Sweden",
    "Switzerland": "Call 117 for scam prevention hotline in Switzerland",
    "Syria": "Call 112 for scam prevention hotline in Syria",
    "Taiwan": "Call 165 for scam prevention hotline in Taiwan",
    "Tajikistan": "Call 112 for scam prevention hotline in Tajikistan",
    "Tanzania": "Call 112 for scam prevention hotline in Tanzania",
    "Thailand": "Call 191 for scam prevention hotline in Thailand",
    "Togo": "Call 117 for scam prevention hotline in Togo",
    "Tonga": "Call 911 for scam prevention hotline in Tonga",
    "Trinidad and Tobago": "Call 999 for scam prevention hotline in Trinidad and Tobago",
    "Tunisia": "Call 197 for scam prevention hotline in Tunisia",
    "Turkey": "Call 155 for scam prevention hotline in Turkey",
    "Turkmenistan": "Call 102 for scam prevention hotline in Turkmenistan",
    "Tuvalu": "Call 911 for scam prevention hotline in Tuvalu",
    "Uganda": "Call 999 for scam prevention hotline in Uganda",
    "Ukraine": "Call 102 for scam prevention hotline in Ukraine",
    "United Arab Emirates": "Call 901 for scam prevention hotline in the United Arab Emirates",
    "United Kingdom": "Call 0300 123 2040 for scam prevention hotline in the United Kingdom",
    "United States": "Call 1-877-FTC-HELP (1-877-382-4357) for scam prevention hotline in the United States",
    "Uruguay": "Call 0800-1011 for scam prevention hotline in Uruguay",
    "Uzbekistan": "Call 102 for scam prevention hotline in Uzbekistan",
    "Vanuatu": "Call 112 for scam prevention hotline in Vanuatu",
    "Vatican City": "Call 113 for scam prevention hotline in Vatican City",
    "Venezuela": "Call 911 for scam prevention hotline in Venezuela",
    "Vietnam": "Call 113 for scam prevention hotline in Vietnam",
    "Yemen": "Call 199 for scam prevention hotline in Yemen",
    "Zambia": "Call 991 for scam prevention hotline in Zambia",
    "Zimbabwe": "Call 994 for scam prevention hotline in Zimbabwe"
  };

  // Get the hotline information for the selected country
  var selectedHotline = hotlineData[selectedCountry];

  // Display the hotline information
  hotlineInfo.textContent = selectedHotline;
}

// Attach the updateHotline function to the change event of the country select dropdown
var countrySelect = document.getElementById("countrySelect");
countrySelect.addEventListener("change", updateHotline);

// Call the updateHotline function initially to display the hotline information for the default selected country
updateHotline();